cart/urls.py
from django.contrib import admin
from django.urls import path
from cart.views import  AddToCartUpdateView, CartListView

app_name = 'cart'
urlpatterns = [
    path('add/<int:pk>/', AddToCartUpdateView.as_view(), name='add'),
    path('list/', CartListView.as_view(), name='list'),
]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [#ссылки должны идти от частного к общему
    path('admin/', admin.site.urls),
    path('', include('refers.urls')),
    path('', include('books.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls'), name = 'cart'), #, namespace='cart'
    path('order/', include('order.urls')), #, namespace='order'
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/urls.py
from django.contrib import admin
from django.urls import path
from order.views import  OrderCreate, OrderDone

app_name = 'order'
urlpatterns = [
    path('checkout/', OrderCreate.as_view(), name='create'),
    path('checkout/thanks', OrderDone.as_view(), name='created'),
]

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from books.models import Book
# Create your models here.
User = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name = "Клиент",
        related_name = "carts",
        on_delete = models.PROTECT)
    objects = models.Manager()
    
    def total_price(self):
        books = self.books.all()
        total = 0
        for book in books:
            total += book.price
        return total

class BookInCart(models.Model):
    book = models.ForeignKey(
        Book,
        verbose_name = "Книга",
        related_name = "books_in_carts",
        on_delete = models.PROTECT
    )
    cart = models.ForeignKey(
        Cart, 
        verbose_name = "Корзина", 
        related_name = "books", 
        on_delete = models.PROTECT
    )
    quantity = models.IntegerField(
        verbose_name = "Количество", 
        default=1
    )
    price = models.DecimalField(
        verbose_name = "Цена, BYN", 
        max_digits=10, 
        decimal_places=2
    )
    objects = models.Manager()

    def __str__(self):
        return f"{self.book.name} * {self.quantity} шт."

cart/forms.py
from django.forms import ModelForm
from cart.models import BookInCart

class BookInCartForm(ModelForm):
    class Meta:
        model = BookInCart
        fields = [
            #'book',
            #'cart',
            'quantity',
            #'price',
        ]

cart/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView
from cart.models import BookInCart, Cart
from books.models import Book
#from django.contrib.auth.models import User
from cart.forms import BookInCartForm
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model

User = get_user_model()

class AddToCartUpdateView(UpdateView):
    model = BookInCart
    form_class = BookInCartForm
    template_name = 'cart/add_to_cart.html'
    success_url = '/cart/list/' 
    def get_object(self):
        book_to_add = self.kwargs.get('pk')
        #if exists
        cart_id = self.request.session.get('cart_id')
        if not cart_id:
            if self.request.user.is_anonymous:
                user = User.objects.get(pk=11)
                cart = Cart.objects.create(user=user)
                self.request.session['cart_id'] = cart.pk
            else:
                user = self.request.user
                cart = Cart.objects.create(user=self.request.user)
                self.request.session['cart_id'] = cart.pk
        else:
            cart = Cart.objects.get(pk=cart_id)
        book = Book.objects.get(pk=book_to_add)
        book_in_cart, created = BookInCart.objects.get_or_create(
            book = book,
            cart = cart,
            defaults={'price': book.price}
        )
        if not created:
            book_in_cart.price = book.price * book_in_cart.quantity
            book_in_cart.quantity = book_in_cart.quantity + 1
            book_in_cart.save()
        return book_in_cart

    def form_valid(self, form, **kwargs):
        quantity = form.cleaned_data.get('quantity')
        price = self.object.book.price
        total_price = quantity * price
        self.object.price = total_price
        #self.object.save() -  использовать если не работает без предварительного сохранения
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class CartListView(TemplateView):
    model = Cart
    template_name = "cart/list.html"
    #success_url = '/order/checkout/' 
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cart_id = self.request.session.get('cart_id')
        cart = None
        if cart_id:
            cart = Cart.objects.get(pk=cart_id)
        context['cart'] = cart
        context['title'] = 'Корзина для заказа'
        context['action'] = 'Пожалуйста, проверьте Ваш заказ'
        return context

cart/templates/cart/add_to_cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Добавить в корзину
{% endblock %}

{% block body %}
<h1> <center>Добавить в корзину</center> </h1>
<h5 class="p-3 mb-2 bg-light text-info"> {{object.book.author}} "{{object.book.name}}" </h5>
<small>
<p> Количество книг, доступное к заказу: <br>{{object.book.quantity_for_sale}} </p>  
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info btn-sm">Сохранить</button>
</form>
</small>
{% endblock body %}

cart/templates/cart/list.html
{% extends 'base.html' %}
{% block title%}
Корзина для заказа
{% endblock%}

{% block body %}
<h2 class="p-3 mb-2 bg-light text-info"><center>Корзина для заказа</center></h2>
<br>
<small>
<h5>Пожалуйста, проверьте Ваш заказ:</h5>
<br>
<table class="table table-striped">
    <thead class="table table-info">
      <tr>
        <th scope="col" >Наименование</th>
        <th scope="col" >Количество</th>
        <th scope="col">Цена, BYN</th>
      </tr>
    </thead>
    <tbody>
      {% for book_in_cart in  cart.books.all %}
      <tr>
        <td> <a style="color: black" href='/book/{{ book_in_cart.book.pk }}/'>{{book_in_cart.book.author}} "{{book_in_cart.book.name}}" </a></td>
        <td> <a style="color: black" href='/cart/add/{{ book_in_cart.book.pk }}/'>{{book_in_cart.quantity}} </a></td>
        <td> {{book_in_cart.price}} </td>
      </tr>    
      {% endfor %}
    </tbody>
  </table>
<h6 class="p-2 mb-1 bg-light">Сумма заказа: {{cart.total_price}} BYN</h6></small>
<br>
<a class="btn btn-outline-info btn-sm" href="{% url 'book-list' %}" role="button"><small>Добавить в корзину</small></a>
<a class="btn btn-outline-info btn-sm" href="{% url 'order:create' %}" role="button"><small>Оформить заказ</small></a> 


{% endblock%}