books/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import JournalHome, JournalDetailView, JournalListView, JournalCreateView, JournalUpdateView, JournalDeleteView
from books.views import BookHome, BookDetailView, BookListView, BookCreateView, BookUpdateView, BookDeleteView, HomePageView, SearchView
from django.conf.urls.static import static

urlpatterns = [
    path('book/', BookHome.as_view(), name='book-home'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='select-book'),
    path('book/list/', BookListView.as_view(), name='book-list'),
    path('book/create/', BookCreateView.as_view(), name='create-book'),
    path('book/update/<int:pk>/', BookUpdateView.as_view(), name='update-book'),
    path('book/delete/<int:pk>/', BookDeleteView.as_view(), name='delete-book'),
    path('journal/', JournalHome.as_view(), name='journal-home'),
    path('journal/<int:pk>/', JournalDetailView.as_view(), name='select-journal'),
    path('journal/list/', JournalListView.as_view(), name='journal-list'),
    path('journal/create/', JournalCreateView.as_view(), name='create-journal'),
    path('journal/update/<int:pk>/', JournalUpdateView.as_view(), name='update-journal'),
    path('journal/delete/<int:pk>/', JournalDeleteView.as_view(), name='delete-journal'),
    path('home/', HomePageView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path
from cart.views import  AddToCartUpdateView, CartListView

app_name = 'cart'
urlpatterns = [
    path('add/<int:pk>/', AddToCartUpdateView.as_view(), name='add'),
    path('list/', CartListView.as_view(), name='list'),
]

onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [#ссылки должны идти от частного к общему
    path('admin/', admin.site.urls),
    path('', include('refers.urls')),
    path('', include('books.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls'), name = 'cart'), #, namespace='cart'
    path('order/', include('order.urls')), #, namespace='order'
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

books/models.py
from django.db import models
from refers.models import Genre
from refers.models import PublishingHouse
from refers.models import TypeCover
from refers.models import Author
from refers.models import Serie

def image_folder(instance,filename): #instanse - объект - Book
    filename = instance.slug + '.' + filename.split('.')[1]
    return '{0}/{1}'.format(instance.slug, filename) #return f'books/{instanse.pk}-{filename}'

class Book(models.Model):
    #id/pk = auto increment
    name = models.CharField(
        max_length=200, 
        verbose_name="Наименование")
    description = models.TextField(
        max_length=3000, 
        verbose_name="Описание", 
        blank=True, 
        null=True)
    tag = models.CharField(
        max_length=1000, 
        verbose_name="Тэги для поиска", 
        blank=True, 
        null=True)
    slug = models.SlugField(verbose_name="Slug")
    cover = models.ImageField(upload_to=image_folder, verbose_name="Обложка", null = True, blank = True) #upload_to = 'books/'
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена, BYN")
    author = models.ForeignKey(
        Author,
        verbose_name="Автор",
        related_name = "books",
        on_delete=models.PROTECT)
    serie = models.ForeignKey(
        Serie,
        verbose_name="Серия",
        #on_delete=models.CASCADE удалится жанр, удалится вся книга (тк они связаны)
        #on_delete=models.DO_NOTHING удалится жанр, поле останется пустым для книги
        on_delete=models.PROTECT)#если захотят удалить жанр, будет сопротивляться удалению
    genre = models.ManyToManyField(
        Genre,
        verbose_name="Жанр")
    year = models.IntegerField(verbose_name="Год издания")
    page = models.IntegerField(verbose_name="Количество страниц")
    type_cover = models.ForeignKey(
        TypeCover,
        verbose_name="Переплёт",
        on_delete=models.PROTECT)
    book_format = models.CharField(max_length=50, verbose_name="Формат")
    book_ISBN = models.CharField(max_length=50, verbose_name="ISBN")
    weight_gram = models.IntegerField(verbose_name="Вес, гр")
    age_restrictions = models.CharField(max_length=50, verbose_name="Возрастные ограничения")
    publishing_house = models.ForeignKey(
        PublishingHouse,
        verbose_name="Издательство",
        on_delete=models.PROTECT) #если захотят удалить издательство, будет сопротивляться удалению
    quantity_for_sale = models.IntegerField(verbose_name="Количество книг в наличии")
    available = models.BooleanField(default=True, verbose_name="Доступно к заказу")
    rating = models.FloatField(verbose_name="Рейтинг")
    created = models.DateTimeField( #date type DateField or DateTimeField
        auto_now=False,
        auto_now_add=True,
        verbose_name="Дата создания")
    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        verbose_name="Дата последнего изменения")
    objects = models.Manager()

    def get_absolute_url(self):
        return f'/book/{self.pk}/'

    def __str__(self):
        return self.name

class Journal(models.Model):
    name = models.CharField(max_length=200, verbose_name="Наименование")
    number = models.IntegerField(verbose_name="Выпуск")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена, BYN")
    month = models.CharField(max_length=50, verbose_name="Месяц")
    year = models.IntegerField(verbose_name="Год издания")
    page = models.IntegerField(verbose_name="Количество страниц")
    available = models.BooleanField(default=True, verbose_name="Доступно к заказу")
    created = models.DateTimeField( #date type DateField or DateTimeField
        auto_now=False,
        auto_now_add=True,
        verbose_name="Дата создания")
    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False,
        verbose_name="Дата последнего изменения")
    
    def get_absolute_url(self):
        return f'/journal/{self.pk}/'

    def __str__(self):
        return self.name

books/forms.py
from django.forms import ModelForm
from books.models import Book, Journal

class BookCreateForm(ModelForm):
    class Meta:
        model = Book
        fields = [
            'name', 
            'slug', 
            'cover', 
            'price', 
            'author', 
            'serie', 
            'genre', 
            'year', 
            'page', 
            'type_cover', 
            'book_format', 
            'book_ISBN',
            'weight_gram',
            'age_restrictions',
            'publishing_house',
            'quantity_for_sale',
            'available',
            'rating',
            'description',
            'tag',
        ]
 
class JournalCreateForm(ModelForm):
    class Meta:
        model = Journal
        fields = [
        'name',
        'number',
        'price',
        'month',
        'year',
        'page',
        'available',
        ]

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, DeletionMixin
from .forms import BookCreateForm, JournalCreateForm
from .models import Book, Journal
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q

#КНИГИ
class BookHome(TemplateView):
    template_name = 'book/home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class BookDetailView(DetailView):
    model = Book

class BookListView(ListView):
    model = Book
    #pagenation
    template_name = 'book/list.html'

class BookCreateView(PermissionRequiredMixin, CreateView):
    model = Book
    form_class = BookCreateForm
    template_name = 'book/create.html'
    permission_required='books.add_book'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = "Создание нового объекта:"
        return context

class BookUpdateView(PermissionRequiredMixin, UpdateView):
    model = Book
    form_class = BookCreateForm 
    template_name = 'book/create.html'
    permission_required='books.change_book'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = "Редактирование объекта:"
        return context

class BookDeleteView(PermissionRequiredMixin, DeleteView):
    model = Book
    template_name = 'book/delete.html'
    success_url = '/book/list/'
    permission_required='books.delete_book'

#ЖУРНАЛЫ
class JournalHome(TemplateView):
    template_name = 'journal/home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class JournalDetailView(DetailView):
    model = Journal

class JournalListView(ListView):
    model = Journal
    template_name = 'journal/list.html'

class JournalCreateView(PermissionRequiredMixin, CreateView):
    model = Journal
    form_class = JournalCreateForm
    template_name = 'journal/create.html'
    permission_required='books.add_journal'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = "Создание нового объекта:"
        return context

class JournalUpdateView(PermissionRequiredMixin, UpdateView):
    model = Journal
    form_class = JournalCreateForm 
    template_name = 'journal/create.html'
    permission_required='books.change_journal'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = "Редактирование объекта:"
        return context

class JournalDeleteView(PermissionRequiredMixin, DeleteView):
    model = Journal
    template_name = 'journal/delete.html'
    success_url = '/journal/list/'
    permission_required='books.delete_journal'

#Главная страница
class HomePageView(ListView):
    model = Book
    form_class = BookCreateForm
    template_name = 'book/home_page.html'

#Поиск
class SearchView(View):
    template_name = 'book/search.html'
    model = Book
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('q')
        found = Book.objects.filter(
            Q(name__icontains=query)|
            Q(tag__icontains=query)
        )
        context = {
            'found':found
        }
        return render(self.request, self.template_name, context)

books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %} 

{% block title %}
Выбранная книга
{% endblock title %}

{% block body %}
<h2 class="text-info"> {{object.author }} "{{object.name }}"</h2>

<div class="container px-lg-6">
    <div class="row mx-lg-n6">
      <div class="col py-3 px-lg-4 bg-white">
        <img src="{{ object.cover.url }}" width = '300px'> 
      </div>
      <div class="col py-3 px-lg-4 bg-bg-white">
          <h3 class="text-muted"> Рейтинг Bookstore: {{object.rating }} <i class="far fa-star"></i> </h2>
          <li> <b>Жанр</b>: {% for genre in object.genre.all %} {{genre.name}} {% endfor %} </li>
          <li> <b>Серия</b>: {{ object.serie }} </li>
          <li> <b>Дата издания</b>: {{ object.year }} </li>
          <li> <b>Количество страниц</b>: {{ object.page }} </li>
          <li> <b>Переплёт</b>: {{ object.type_cover }} </li>
          <li> <b>Формат</b>: {{ object.book_format }} </li>
          <li> <b>ISBN</b>: {{ object.book_ISBN }} </li>
          <li> <b>Вес,гр</b>: {{ object.weight_gram }} </li>
          <li> <b>Возрастные ограничения</b>: {{ object.age_restrictions }} </li>
          <li> <b>Издательство</b>: {{ object.publishing_house }} </li>
          <li> <b>Доступно к заказу</b>: {% if object.available == True %} Да {% elif object.available == False %} Под заказ {% endif %}</li>
          <li> <b>Издательство</b>: {{ object.publishing_house }} </li>
          <a class="nav-link" style="color: rgb(47, 135, 170)" href="{% url 'cart:add' object.pk %}"> {{ object.price }} BYN <i class="fab fa-opencart"></i></a>
          {% if perms.books.delete_book %}<td><a style="color: rgb(47, 135, 170)" href='/book/delete/{{ object.pk }}/'> <i class="fas fa-trash-alt"></i></a></td>{% endif %}
          {% if perms.books.change_book %}<td><a style="color: rgb(47, 135, 170)" href='/book/update/{{ object.pk }}/'> <i class="fas fa-edit"></i></a></td>{% endif %}
      </div> 
    </div>
</div>
{% endblock body %} 

books/templates/books/journal_detail.html
{% extends 'base.html' %}

{% block title %}
Выбранный журнал
{% endblock title %}

{% block body %}
    <h2>{{object.name }} № {{object.number }}, {{object.year }}</h2>
<table class="table table-borderless">
  <thead>
    <tr>
    <th scope="col">Название</th>
    <th scope="col">Номер</th>
    <th scope="col">Цена,BYN</th>
    <th scope="col">Месяц</th>
    <th scope="col">Год издания</th>
    <th scope="col">Количество страниц</th>
    <th scope="col">Доступно к заказу</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td> {{ object.name }}</td>
    <td> {{ object.number }} </td>
    <td> {{ object.price }} </td>
    <td> {{ object.month }} </td>
    <td> {{ object.year }} </td>
    <td> {{ object.page }} </td>
    <td> {{ object.available }} </td>
    </tr> 
  </tbody>
</table>
{% endblock body %} 